spring.application.name=Tests
server.port = 10030

spring.datasource.url= jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.username=cools
spring.datasource.password=1234
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver


mybatis.mapper-locations=classpath:mapper/**/*.xml
mybatis.configuration.map-underscore-to-camel-case=true

spring.devtools.livereload.enabled=true
spring.devtools.restart.enabled=false

spring.thymeleaf.cache=false
spring.thymeleaf.enabled=true
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html