spring.application.name=receiptocr2



spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

spring.datasource.url=jdbc:mariadb://192.168.0.165:3306/ocr
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver


spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.cache=false

mybatis.mapper-locations=classpath:mapper/**/*.xml
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.configuration.default-statement-timeout=30
mybatis.configuration.jdbc-type-for-null=VARCHAR
mybatis.configuration.call-setters-on-nulls=true
mybatis.configuration.auto-mapping-unknown-column-behavior=WARNING



# CLOVA OCR
clova.secret= 
clova.url=
spring.servlet.multipart.max-file-size=200MB

server.port = 8090